bin.includes = META-INF/,\
               plugin.xml,\
               com.archimatetool.designdecision.jar,\
               img/
jars.compile.order = com.archimatetool.designdecision.jar
source.com.archimatetool.designdecision.jar = src/
output.com.archimatetool.designdecision.jar = bin/